name: Actualizar Análisis (Diario 17:00)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: pip install requests beautifulsoup4 lxml

      - name: Ejecutar Análisis
        run: python analisis.py

      - name: Guardar Base de Datos y HTML
        run: |
          git config --global user.name "Bot Analisis"
          git config --global user.email "actions@github.com"
          
          # Añadimos los archivos clave
          git add licitaciones_db.json
          git add backups/
          git add analisis.html
          
          # Hacemos commit
          git commit -m "Update: Análisis diario" || exit 0
          
          # ANTICONFLICTOS
          git pull origin main --no-rebase -s recursive -X ours
          
          git push
