name: Actualizar Licitaciones (Horario)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 8-17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librer√≠as
        run: pip install requests beautifulsoup4 lxml

      - name: Ejecutar Licitaciones
        run: python main.py

      - name: Guardar cambios
        run: |
          git config --global user.name "Bot Licitaciones"
          git config --global user.email "actions@github.com"
          
          git add index.html
          git commit -m "Update: Licitaciones horarias" || exit 0
          
          # --- ANTICONFLICTOS ---
          git pull origin main --no-rebase -s recursive -X ours
          # ----------------------
          
          git push
