name: Actualizar Dashboard Licitaciones

on:
  schedule:
    - cron: '0 7 * * *' # Se ejecuta a las 07:00 UTC todos los días
  workflow_dispatch: # Permite que le des a un botón para actualizar manualmente si quieres

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chequear código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script
        run: python main.py

      - name: Guardar cambios (Publicar web)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          git commit -m "Actualización automática de datos" || exit 0
          git push
