name: Actualizar Licitaciones

on:
  schedule:
    # 8-17 UTC equivale a 9-18 Hora España Invierno
    # Se ejecutará cada hora en el minuto 0
    - cron: '0 8-17 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías necesarias
        run: |
          pip install requests beautifulsoup4 lxml

      - name: Ejecutar el script (main.py)
        run: python main.py

      - name: Guardar y publicar cambios
        run: |
          git config --global user.name "Actualizador Automático"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Actualización automática de datos" || echo "No hubo cambios nuevos"
          git push
