name: Actualizar Licitaciones

on:
  # 1. Se ejecuta al guardar cambios (para probar que funciona)
  push:
    branches:
      - main
  
  # 2. Se ejecuta manualmente (botón)
  workflow_dispatch:
  
  # 3. Se ejecuta automáticamente (Horario)
  # Minuto 0, de 8:00 UTC a 17:00 UTC (9:00 a 18:00 España)
  schedule:
    - cron: '0 8-17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías necesarias
        run: |
          pip install requests beautifulsoup4 lxml

      - name: Ejecutar el script (main.py)
        run: python main.py

      - name: Guardar y publicar cambios
        run: |
          git config --global user.name "Actualizador Automático"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Actualización automática de datos" || echo "No hubo cambios nuevos"
          git push
        run: python analisis.py
